/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.my.company.sistemaclienteservidorrmi.client;

import com.my.company.sistemaclienteservidorrmi.entities.Appointment;
import com.my.company.sistemaclienteservidorrmi.entities.Doctor;
import com.my.company.sistemaclienteservidorrmi.entities.Patient;
import interfaces.IAppointmentInterface;
import interfaces.IDoctorInterface;
import interfaces.IPatientInterface;
import interfaces.IRemoteService;
import java.rmi.RemoteException;
import java.text.SimpleDateFormat;
import java.time.LocalTime;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.ListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sebah
 */
public class AppointmentPanel extends javax.swing.JPanel {
    private IAppointmentInterface appointmentService;
    private IDoctorInterface doctorService;
    private IPatientInterface patientService;
    private Appointment selectedAppointment;
    private DefaultTableModel tablemodel;
    List<Patient> patientsModels;
    List<Doctor> doctorModels;

    /**
     * Creates new form AppointmentPanel
     */
    
    public AppointmentPanel() {
        try {
            appointmentService = Client.getRemoteService().getAppointmentService();
            doctorService = Client.getRemoteService().getDoctorService();
            patientService = Client.getRemoteService().getPatientService();
            initComponents();
            settingUpCustomConfig();
        } catch (RemoteException ex) {
            Logger.getLogger(AppointmentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    public void settingUpCustomConfig(){
        tablemodel = new DefaultTableModel(
                new Object[][] {},
                new String[] {"ID", "Fecha", "Hora", "Motivo", "Medico Asignado", "Paciente Asignado"}
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTable2.setModel(tablemodel);
        loadAppointments(tablemodel);
        
        jButton1.setEnabled(true);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        
        
        
        
        
    }
    
    public void loadAppointments( DefaultTableModel tableModel){
        try {
            tableModel.setRowCount(0);
            List<Appointment> appointments = appointmentService.getAllAppointments();
            for (Appointment appointment : appointments) {
                appointment.getDoctor();
                appointment.getPatient();
                tableModel.addRow(new Object[] {
                        appointment.getId(),
                        appointment.getDate(),
                        appointment.getHour(),
                        appointment.getSubject(),
                        appointment.getDoctor().getName(),
                        appointment.getPatient().getName()
                });
            }
            
            DefaultListModel<String> doctors = new DefaultListModel<>();
            doctorModels = doctorService.getAllDoctors();
            for(Doctor doctor: doctorModels){
                doctors.addElement(doctor.getName()); 
            }
            jList1.setModel(doctors);
            
            DefaultListModel<String> patients = new DefaultListModel<>();
            patientsModels = patientService.getAllPatients();
            
            for(Patient patient: patientsModels){
                patients.addElement(patient.getName());
            }
            jList2.setModel(patients);
            
            
            
        } catch (RemoteException e) {
            JOptionPane.showMessageDialog(this, "Error cargando médicos: " + e.getMessage(),
                    "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        jScrollPane1.setViewportView(jList1);

        jScrollPane2.setViewportView(jList2);

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Hora");

        jLabel2.setText("Fecha");

        jLabel3.setText("Asunto");

        jLabel4.setText("Doctores");

        jLabel5.setText("Pacientes");

        jButton2.setText("Limpiar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Editar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(jTable2);

        jButton5.setText("Recargar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(79, 79, 79))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jTextField2)
                                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jButton1)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(90, 90, 90)
                                        .addComponent(jButton4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jButton2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton3)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(jButton5)
                        .addGap(29, 29, 29)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(jButton3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton4)
                            .addComponent(jButton1)
                            .addComponent(jButton5))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        cleanInputs();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            manageAppointment(selectedAppointment, jList1.getSelectedIndex(), jList2.getSelectedIndex() , getData(jTextField3),getDate(),gethour() );
            
            appointmentService.updateAppointment(selectedAppointment);
            cleanInputs();
            loadAppointments(tablemodel);
        } catch (Exception ex) {
            Logger.getLogger(AppointmentPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Algo salio mal", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            appointmentService.deleteAppointment(selectedAppointment.getId());
            cleanInputs();
            loadAppointments(tablemodel);
            
        } catch (RemoteException ex) {
            Logger.getLogger(AppointmentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        selectedAppointment = new Appointment();
        
        try {
            manageAppointment(selectedAppointment, jList1.getSelectedIndex(), jList2.getSelectedIndex() , getData(jTextField3),getDate(),gethour() );
            
            appointmentService.createAppointment(selectedAppointment);
            cleanInputs();
            loadAppointments(tablemodel);
        } catch (Exception ex) {
            Logger.getLogger(AppointmentPanel.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Algo salio mal", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int row = jTable2.getSelectedRow();
        try {
            selectedAppointment = appointmentService.getAppointment((Integer)tablemodel.getValueAt(row, 0));
            String fechaFormateada = new SimpleDateFormat("yyyy-MM-dd").format(selectedAppointment.getDate());
            jTextField2.setText(fechaFormateada);
            jTextField1.setText(selectedAppointment.getHour().toString());
            jTextField3.setText(selectedAppointment.getSubject());
            
            int docint = getSelectedDoctor(doctorModels, selectedAppointment.getDoctor().getId());
            jList1.setSelectedIndex(docint);
                    

            int patint =getSelectedPatient(patientsModels, selectedAppointment.getPatient().getId());
            jList2.setSelectedIndex(patint);
            
            jButton1.setEnabled(false);
            jButton2.setEnabled(true);
            jButton3.setEnabled(true);
            jButton4.setEnabled(true);
        } catch (RemoteException ex) {
            Logger.getLogger(AppointmentPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        loadAppointments(tablemodel);
    }//GEN-LAST:event_jButton5ActionPerformed

    public void cleanInputs(){
        selectedAppointment = null;

        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        
        
        jButton1.setEnabled(true);
        jButton2.setEnabled(false);
        jButton3.setEnabled(false);
        jButton4.setEnabled(false);
        
        jList1.clearSelection();
        jList2.clearSelection();

    }
    
    public String getData(JTextField jTextField){
        String data = jTextField.getText().trim();
        if(data.isEmpty()){
            return null;
        }
        return data;
    }
    public Date getDate(){
        String fechaTexto = jTextField2.getText().trim();
        SimpleDateFormat formato = new SimpleDateFormat("yyyy-MM-dd");
        
        try {
            Date fecha = formato.parse(fechaTexto);
            return fecha;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Fecha invalida", "Advertencia", JOptionPane.WARNING_MESSAGE);
        }
        return null;

    }
    
    public LocalTime gethour(){
        try {
            LocalTime time = LocalTime.parse(jTextField1.getText().trim());
                return time;

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Hora invalida", "Advertencia", JOptionPane.WARNING_MESSAGE);

        }
        
        return null;
    }
    
    
    public void manageAppointment(Appointment appointment, int doctor, int patient, String subject, Date date, LocalTime time) throws Exception{
        if(subject == null || date == null || time == null){
            throw new Exception();
        }
        
        appointment.setDate(date);
        appointment.setHour(time);
        appointment.setSubject(subject);
        
        Doctor doc = doctorModels.get(doctor);
      
        Patient pat = patientsModels.get(patient);
        appointment.setDoctor(doc);
        appointment.setPatient(pat);
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    
    private int getSelectedPatient(List<Patient> patientsModels, int id) {
        int i = 0;
        for(Patient pat : patientsModels){
            if(pat.getId() == id){
                return i;
            }
            i++;
        }
        
        return -1;
    }
    private int getSelectedDoctor(List<Doctor> doctorModels, int id){
        int i = 0;
        for(Doctor doc : doctorModels){
            if(doc.getId() == id){
                return i;
            }
            i++;
        }
        
        return -1;
    }
}
